name: meal_manager
description: Lecka Schmecka, alla

publish_to: 'none' # Remove to Publish

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family:  CustomIcons
      fonts:
       - asset: assets/fonts/CustomIcons.ttf

  assets:
    - assets/
    - assets/images/
    - assets/images/avatars/
    - assets/images/avatars/hair/
    - assets/images/recipes/
